//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intec.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Propiedades = new HashSet<Propiedades>();
        }
    
        public int IdCliente { get; set; }
        public string NumeroDeIdentificacion { get; set; }
        public int IdTipoDocumento { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoCel1 { get; set; }
        public string TelefonoCel2 { get; set; }
        public string Direccion { get; set; }
        public string IdCiudad { get; set; }
        public int IdUso { get; set; }
        public string Foto { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public int IdTipoPersona { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public string NumeroIdentificacion { get; set; }
        public int IdTipoIdentificacion { get; set; }
    
        public virtual TiposDocumento TiposDocumento { get; set; }
        public virtual TiposPersona TiposPersona { get; set; }
        public virtual TiposIdentificacion TiposIdentificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Propiedades> Propiedades { get; set; }
    }
}
