//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intec.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsecutivosFormatos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsecutivosFormatos()
        {
            this.FormatosVisita = new HashSet<FormatosVisita>();
        }
    
        public int IdFormato { get; set; }
        public int Consecutivo { get; set; }
        public Nullable<int> IdInspector { get; set; }
        public string IdEstadoConsecutivoInspector { get; set; }
        public string IdVisita { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
    
        public virtual Formatos Formatos { get; set; }
        public virtual EstadosConsecutivosInspector EstadosConsecutivosInspector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormatosVisita> FormatosVisita { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
