//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intec.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsecutivosFormatos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsecutivosFormatos()
        {
            this.FormatosVisita = new HashSet<FormatosVisita>();
        }
    
        public int IdFormato { get; set; }
        public int Consecutivo { get; set; }
        public Nullable<int> IdInspector { get; set; }
        public string IdEstadoConsecutivoInspector { get; set; }
        public string IdVisita { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
    
        public virtual Formatos Formatos { get; set; }
        public virtual EstadosConsecutivosInspector EstadosConsecutivosInspector { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormatosVisita> FormatosVisita { get; set; }
    }
}
