//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intec.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiposVisita
    {
        public int IdVisita { get; set; }
        public int Secuencia { get; set; }
        public int IdEquipo { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Visitas Visitas { get; set; }
    }
}
