//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intec.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KardexPapeleria
    {
        public int IdEntradaPapeleria { get; set; }
        public string IdTipoMovimiento { get; set; }
        public int IdFormato { get; set; }
        public Nullable<int> IdInspector { get; set; }
        public int ConsecutivoInicial { get; set; }
        public int ConsecutivoFinal { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
    
        public virtual TiposMovimientoKardex TiposMovimientoKardex { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
