//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intec.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratorios
    {
        public int IdLaboratorio { get; set; }
        public string Laboratorio { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public string Nit { get; set; }
        public int DV { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
    }
}
