//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intec.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propiedades
    {
        public int IdPropiedades { get; set; }
        public int IdCliente { get; set; }
        public string Direccion { get; set; }
        public int IdUso { get; set; }
        public string Telefono { get; set; }
        public string Foto { get; set; }
        public string Observaciones { get; set; }
        public int IdTipoPropiedad { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual TiposPropiedades TiposPropiedades { get; set; }
        public virtual UsosPropiedades UsosPropiedades { get; set; }
    }
}
