//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intec.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudContactenos
    {
        public int IdSolicitudContactenos { get; set; }
        public bool PQRA { get; set; }
        public string NombreCompleto { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ip { get; set; }
        public string city { get; set; }
        public string country { get; set; }
    }
}
