//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intec.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TramitesEquipo
    {
        public int IdEquipo { get; set; }
        public int Secuencia { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdInspector { get; set; }
        public string Tramite { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
