//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intec.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosEquipos
    {
        public int IdInspector { get; set; }
        public int IdEquipo { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
        public int IdUsuarioAsigna { get; set; }
        public string Estado { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
